### ISSUE TITLE
: Number must be either non-negative and less than or equal to Int32.MaxValue or -1

### ISSUE THREAD

**Issue by workmans** [nacos-group/nacos-sdk-csharp#107]
Unhandled exception. System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1. (Parameter 'dueTime')
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at Nacos.V2.Naming.Core.ServiceInfoUpdateService.<>c__DisplayClass11_0.<<UpdateTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by catcherwong** [comment]
@workmans  Thanks for your interest in this project.

This bug was fixed in the newest pre-release version. Please have a try.
