### ISSUE TITLE
使用v2版本注册报错，原来的v1 的 services.AddNacosAspNetCore(_config); 正常

### ISSUE THREAD

**Issue by pccai** [nacos-group/nacos-sdk-csharp#114]
info: Nacos.V2.Naming.NacosNamingService[0]
      [REGISTER-SERVICE]  registering service gate with instance Instance{instanceId='', ip='172.20.32.1', port=18068, weight=100, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='gate', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"5.0.7","HOST_OS":"Microsoft Windows NT 10.0.19043.0","author":"zhangsan","cc":"XX.Web","md":"Developer","tp":"XXPlatform","ver":"6.0.1.30"}}
2021-06-15 16:51:38.0632|Info|1|register instance to nacos server, 【Instance{instanceId='', ip='172.20.32.1', port=18068, weight=100, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='gate', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"5.0.7","HOST_OS":"Microsoft Windows NT 10.0.19043.0","author":"cai","cc":"XX.Web","md":"Developer","tp":"XXPlatform","ver":"6.0.1.30"}}】|
2021-06-15 16:51:38.0849|Info|1|[REGISTER-SERVICE]  registering service gate with instance Instance{instanceId='', ip='172.20.32.1', port=18068, weight=100, healthy=True, enabled=True, ephemeral=True, clusterName='DEFAULT', serviceName='gate', metadata={"preserved.register.source":"ASPNET_CORE","DOTNET_VERSION":"5.0.7","HOST_OS":"Microsoft Windows NT 10.0.19043.0","author":"zhangsan","cc":"XX.Web","md":"Developer","tp":"XXPlatform","ver":"6.0.1.30"}}|
fail: Nacos.AspNetCore.V2.RegSvcBgTask[0]
      register instance error, count = 1
      Nacos.V2.Exceptions.NacosException: Request nacos server failed: -401, Client not connected,current status: 2
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RequestToServer[T](AbstractNamingRequest request)
         at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.Remote.NamingClientProxyDelegate.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
         at Nacos.V2.Naming.NacosNamingService.RegisterInstance(String serviceName, String groupName, Instance instance)
         at Nacos.AspNetCore.V2.RegSvcBgTask.StartAsync(CancellationToken cancellationToken)

版本： 
		<PackageReference Include="nacos-sdk-csharp.AspNetCore" Version="1.1.0" />
		<PackageReference Include="nacos-sdk-csharp.IniParser" Version="1.0.3" />

**Comment by pccai** [comment]
<PackageReference Include="nacos-sdk-csharp.AspNetCore" Version="1.1.0" />
		<PackageReference Include="nacos-sdk-csharp.IniParser" Version="1.0.3" />

**Comment by pccai** [comment]
抱歉，看到方案了：

没和服务端建立好连接。
检查一下服务端是否是2.x的版本，
如果不是，请把 UseRpc 相关的配置设置成 false;
如果是，请检查服务端是否暴露出grpc的端口(nacos的端口+1000)；
