### ISSUE TITLE
Could not load type 'Nacos.PreservedMetadataKeys'

### ISSUE THREAD

**Issue by code-jar** [nacos-group/nacos-sdk-csharp#172]
## Describe what happened (or what feature you want)
`nacos-sdk-csharp.Extensions.Configuration`  1.2.0 update to 1.3.0，An exception occurred 
```
Could not load type 'Nacos.PreservedMetadataKeys' from assembly 'Nacos, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'

   at Nacos.AspNetCore.V2.RegSvcBgTask.<StartAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Nacos.AspNetCore.V2.RegSvcBgTask.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

## Tell us your environment

- nacos-sdk-csharp version: [e.g. 1.3.0]
- modular : [config]
- nacos server version: [2.0.3]
- how to host nacos server : [pc]

**Comment by code-jar** [comment]
update nacos-sdk-csharp.AspNetCore fixed
