### ISSUE TITLE
参考文档写了一个Demo程序启动报错 MS Config Query config error, dataid=demo, group=DEFAULT_GROUP, tenant=(null)

### ISSUE THREAD

**Issue by Gavinluo** [nacos-group/nacos-sdk-csharp#179]
```
info: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [subscribe] demo+DEFAULT_GROUP+SCM-Core
info: Nacos.V2.Config.NacosConfigService[0]
      [4c9c76d1-65b2-4ad9-8f9d-a089f5d29289_config-0] Connected,notify listen context...
warn: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      MS Config Query config error, dataid=demo, group=DEFAULT_GROUP, tenant=(null)
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.IO.StringReader..ctor(String s)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
   at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
fail: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      Load config error
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.IO.StringReader..ctor(String s)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
   at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Gavin\source\repos\WebApplication26\WebApplication26
```

## Related code

```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "common",
        "Group": "DEFAULT_GROUP"
      },
      {
        "Optional": false,
        "DataId": "demo",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Namespace": "SCM-Core", // Please set the value of Namespace ID !!!!!!!!: null,
    "ServerAddresses": [ "http://localhost:8848/" ],
    "UserName": "nacos",
    "Password": "nacos",
    "AccessKey": "",
    "SecretKey": "",
    "EndPoint": ""
  }
}
```

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args).ConfigureAppConfiguration((context, builder) =>
            {
                var c = builder.Build();
                builder.AddNacosV2Configuration(c.GetSection("NacosConfig"));
            }).ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
```

## Tell us your environment

- nacos-sdk-csharp version:1.3.1
- modular : [e.g. naming/config/msconfig/....]
- nacos server version: 2.0.2
- how to host nacos server : docker

nacos 配置如下
![image](https://user-images.githubusercontent.com/1356485/151524917-4e2ad53e-9676-440d-865f-5e976e6b15b8.png)

![image](https://user-images.githubusercontent.com/1356485/151524853-d2f3f290-f5a9-4fac-9733-627cdefbffee.png)

**Comment by Gavinluo** [comment]
问题已找到，是我的namespace 写的别名，没有写id
