### ISSUE TITLE
Load config error: Collection was modified after the enumerator was instantiated.

### ISSUE THREAD

**Issue by SwingCosmic** [nacos-group/nacos-sdk-csharp#192]
## Describe what happened (or what feature you want)

程序启动时获取nacos配置有一定概率报错 
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.

- 出现随机，在Docker中运行触发概率更大
- 出错后可能正常运行，也可能丢失配置，也可能产生层次错误的配置（见下面出错配置）
- 在.Net Core 3.1、.NET5和.NET6上均出现，Nacos 1.x和2.0上均有发生，nacos-sdk-csharp1.x一直存在
- 未开启GRPC，使用YAML parser

```
info: Nacos.V2.Config.NacosConfigService[0]
      [fixed-nacos.storage.svc.cluster.local_8848] [subscribe] dicloud+DEFAULT_GROUP
info: Nacos.V2.Config.NacosConfigService[0]
      [fixed-nacos.storage.svc.cluster.local_8848] [polling-resp] config changed. dataId=dicloud, group=DEFAULT_GROUP
info: Nacos.V2.Config.NacosConfigService[0]
      [fixed-nacos.storage.svc.cluster.local_8848] [data-received] dataId=dicloud, group=DEFAULT_GROUP, tenant=(null), md5=de20f081bf19a747dfdba8101f9c6e24, content=dataSource:
          DiSystem: 
              type: MySQL
              configuration: "server=mysql.storage.svc.clus..., type=yaml
warn: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      MS Config Query config error, dataid=dicloud, group=DEFAULT_GROUP, tenant=(null)
      System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
         at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
         at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
         at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
         at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
         at System.String.Join(String separator, IEnumerable`1 values)
         at Microsoft.Extensions.Configuration.ConfigurationPath.Combine(IEnumerable`1 pathSegments)
         at Nacos.YamlParser.YamlConfigurationStringParser.EnterContext(String context)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlScalarNode(String context, YamlScalarNode yamlValue)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlNode(String context, YamlNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(YamlMappingNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(String context, YamlMappingNode yamlValue)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlNode(String context, YamlNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(YamlMappingNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(String context, YamlMappingNode yamlValue)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlNode(String context, YamlNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(YamlMappingNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
fail: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      Load config error
      System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
         at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
         at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
         at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
         at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
         at System.String.Join(String separator, IEnumerable`1 values)
         at Microsoft.Extensions.Configuration.ConfigurationPath.Combine(IEnumerable`1 pathSegments)
         at Nacos.YamlParser.YamlConfigurationStringParser.EnterContext(String context)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlScalarNode(String context, YamlScalarNode yamlValue)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlNode(String context, YamlNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(YamlMappingNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(String context, YamlMappingNode yamlValue)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlNode(String context, YamlNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(YamlMappingNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(String context, YamlMappingNode yamlValue)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlNode(String context, YamlNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.VisitYamlMappingNode(YamlMappingNode node)
         at Nacos.YamlParser.YamlConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
```

报错后取到的配置（层级错误的版本）
```
...
dataSource=
dataSource:dataSource=
dataSource:dataSource:DiSystem=
dataSource:dataSource:DiSystem:DiSystem=
dataSource:dataSource:DiSystem:DiSystem:type=
dataSource:dataSource:DiSystem:DiSystem:type:type=MySQL
dataSource:dataSource:DiSystem:DiSystem:type:configuration=server=mysql.storage.svc.cluster.local...
```
## Describe what you expected to happen

正常获取到配置且不发生错误

## How to reproduce it (as minimally and precisely as possible)

1. 搭建Nacos server，添加如上配置(YAML)
2. 新建ASP.NET Core WebAPI 项目，使用下面的appsettings.json和入口代码
3. Docker build构建容器，然后反复重启容器检查日志输出

## Related code

```JSON
{
  "nacos": {
    "ServerAddresses": [
      "http://nacos.storage.svc.cluster.local:8848"
    ],
    "DefaultTimeOut": 15000,
    "Namespace": "",
    "ListenInterval": 5000,
    "ServiceName": "metadata",
    "Weight": 1,
    "Metadata": {
      "preserved.register.source": "ASPNET_CORE"
    },
    "ConfigUseRpc":  false,
    "NamingUseRpc": false,
    "Listeners": [
      {
        "Optional": false,
        "DataId": "dicloud",
        "Group": "DEFAULT_GROUP"
      }
    ]
  }
}
```

```csharp
var builder = WebApplication.CreateBuilder(args);

var nacosConfig = builder.Configuration.GetSection("nacos");
builder.Configuration.AddNacosV2Configuration(nacosConfig, Nacos.YamlParser.YamlConfigurationStringParser.Instance);
Console.WriteLine(string.Join("\n", builder.Configuration.AsEnumerable().Select(p => p.Key + "=" + p.Value)));
```

## Tell us your environment

- nacos-sdk-csharp version: 1.0+(current 1.2.1)
- modular : naming, config
- nacos server version: 2.0+
- how to host nacos server : k8s standalone

**Comment by catcherwong** [comment]
用 docker-compose 模拟了一下，没有重现出来。 示例仓库：[nacos-csharp-192](https://github.com/catcherwong-archive/2022/tree/main/nacos-csharp-192)

![1647789456(1)](https://user-images.githubusercontent.com/8394988/159169421-5655f00f-d61d-40ce-9d59-63674d5eca57.png)

方便的话把配置内容脱敏后贴一下。看这个错误很像是配置内容无法解析。

**Comment by SwingCosmic** [comment]
> 用 docker-compose 模拟了一下，没有重现出来。 示例仓库：[nacos-csharp-192](https://github.com/catcherwong-archive/2022/tree/main/nacos-csharp-192)
> 
> ![1647789456(1)](https://user-images.githubusercontent.com/8394988/159169421-5655f00f-d61d-40ce-9d59-63674d5eca57.png)
> 
> 方便的话把配置内容脱敏后贴一下。看这个错误很像是配置内容无法解析。



> 用 docker-compose 模拟了一下，没有重现出来。 示例仓库：[nacos-csharp-192](https://github.com/catcherwong-archive/2022/tree/main/nacos-csharp-192)
> 
> ![1647789456(1)](https://user-images.githubusercontent.com/8394988/159169421-5655f00f-d61d-40ce-9d59-63674d5eca57.png)
> 
> 方便的话把配置内容脱敏后贴一下。看这个错误很像是配置内容无法解析。

我试了一下sdk升级到最新版好了，可能是YAML解析器的问题
