### ISSUE TITLE
自动断开重新注册问题

### ISSUE THREAD

**Issue by china9839** [nacos-group/nacos-sdk-csharp#252]
2023-06-17 10:07:43.436 [Warning] [Nacos.V2.Naming.NacosNamingService] Grpc connection disconnect, mark to redo
2023-06-17 10:07:43.436 [Warning] [Nacos.V2.Naming.NacosNamingService] mark to redo completed
2023-06-17 10:07:43.436 [Information] [Nacos.V2.Naming.NacosNamingService] Grpc connection connect
2023-06-17 10:07:48.423 [Information] [Nacos.V2.Naming.NacosNamingService] Redo instance operation REGISTER for "DEFAULT_GROUP"@@"system-service"
2023-06-17 10:07:48.424 [Information] [Nacos.V2.Naming.NacosNamingService] Redo instance operation REGISTER for "DEFAULT_GROUP"@@"system-service"
2023-06-17 10:07:48.431 [Information] [Nacos.V2.Naming.NacosNamingService] Redo subscriber operation

**Comment by china9839** [comment]
应用是.net core3.1 webapi ,Nacos sdk用的是1.2.1版本
系统运行一段时间就会报上边的警告信息，这时这个服务从nacos就请求不进来了

**Comment by catcherwong** [comment]
这个是触发了客户端和服务端的重连机制，做完全 redo 的操作后，服务是会重新注册和被发现的。

**Comment by china9839** [comment]
> 这个是触发了客户端和服务端的重连机制，做完全 redo 的操作后，服务是会重新注册和被发现的。

嗯，大概了解。那么grpc长连接 每5秒钟向nacos发送心跳，假设nacos服务一直正常。那么上边这个问题，有可能是grpcclient链接无法创建，或调用不可达的情况发生吗？

**Comment by china9839** [comment]
> 这个是触发了客户端和服务端的重连机制，做完全 redo 的操作后，服务是会重新注册和被发现的。

主要是什么情况下，能触发这个redo那。
而且redo之后，好像nacos重新注册，有段时间从nacos是调不进来服务的

**Comment by ROMYIM** [comment]
@catcherwong @china9839 我的服务现在也会出现这个问题。突然间就断掉了。而且一直重连失败，要重启容器才行，不知道为什么。nacos-sdk包用的是1.3.5

**Comment by catcherwong** [comment]
@ROMYIM 有具体的日志吗？

**Comment by liangdan862679370** [comment]
> @ROMYIM 有具体的日志吗？

我的问题和他类似用也是1.3.5，nacos版本2.1.1，连接成功后几秒就断了，我看是心跳检测不过，具体日志
[19:30:54.673 scm-std-message-apis-55b4659cc-9m67s Information] [QuantumBootstraper] Host Build Success, Start Run...

[19:30:59.732 scm-std-message-apis-55b4659cc-9m67s Error] [Nacos.V2.Naming.NacosNamingService] [SecurityProxy] login http request failed, url: http://svc-scm-nacos-headless:8848/nacos/v1/auth/users/login

System.Threading.Tasks.TaskCanceledException: The operation was canceled.

   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at Nacos.V2.Security.SecurityProxy.LoginAsync(String server)

[19:30:59.732 scm-std-message-apis-55b4659cc-9m67s Error] [Nacos.V2.Naming.NacosNamingService] [SecurityProxy] login http request failed, url: http://svc-scm-nacos-headless:8848/nacos/v1/auth/users/login

System.Threading.Tasks.TaskCanceledException: The operation was canceled.

   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

**Comment by Await-d** [comment]
有解决办法吗，目前net8项目使用的1.3.5的版本包还是一样有问题，一直提示
Redo instance operation REGISTER for NET@@Ids4
Redo instance operation REGISTER for NET@@Ids4
Redo instance operation REGISTER for NET@@Ids4
