### ISSUE TITLE
NET6 Nacos Sdk  M3芯片的macOS 14.2.1 中获取不到配置值 

### ISSUE THREAD

**Issue by ayewei** [nacos-group/nacos-sdk-csharp#290]
info: Nacos.V2.Config.NacosConfigService[0]
      [fixed-192.168.31.86_8848-DSMcService_Development] [subscribe] GatewayConfig+Development_GROUP+DSMcService_Development
fail: Nacos.V2.Config.NacosConfigService[0]
      [NACOS Exception GET] currentServerAddr: 192.168.31.86:8848
      System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
         at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
         at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
         at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Nacos.V2.Config.Http.ServerHttpAgent.HttpRequest(String path, Dictionary`2 headers, Dictionary`2 paramValues, String encoding, Int64 readTimeoutMs, HttpMethod method)
在Windows下面是可以运行的
![WeChata107a8d09ac620f8ddd9dcbbc07a6f9d](https://github.com/nacos-group/nacos-sdk-csharp/assets/35281200/46255bc0-dc96-4b0c-b344-0a4c27ba10dd)

**Comment by ayewei** [comment]
<img width="442" alt="image" src="https://github.com/nacos-group/nacos-sdk-csharp/assets/35281200/92aad14c-4136-444e-b05d-303124f7b4d7">
<img width="291" alt="image" src="https://github.com/nacos-group/nacos-sdk-csharp/assets/35281200/8102b89d-d2f1-4af1-8a8d-c4acb04da425">
