### ISSUE TITLE
服务注册成功后又断开的问题,导致k8s pod心跳检测失败 一直在重试

### ISSUE THREAD

**Issue by liangdan862679370** [nacos-group/nacos-sdk-csharp#299]
C# 3.1版本
注册成功后 有断开了 然后k8s pod一直重试
报错如下
[Nacos.V2.Naming.NacosNamingService] [SecurityProxy] login http request failed, url: http://svc-scm-nacos-headless:8848/nacos/v1/auth/users/login

System.Threading.Tasks.TaskCanceledException: The operation was canceled.

   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at Nacos.V2.Security.SecurityProxy.LoginAsync(String server)

[19:30:59.732 scm-std-message-apis-55b4659cc-9m67s Error] [Nacos.V2.Naming.NacosNamingService] [SecurityProxy] login http request failed, url: http://svc-scm-nacos-headless:8848/nacos/v1/auth/users/login

System.Threading.Tasks.TaskCanceledException: The operation was canceled.

   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at Nacos.V2.Security.SecurityProxy.LoginAsync(String server)
## Tell us your environment

- nacos-sdk-csharp version: 1.3.5
- modular :[Nacos.V2.Naming.NacosNamingService] [SecurityProxy]
- nacos server version: 2.1.1
- how to host nacos server : k8s

## Anything else we need to know?
有问题随时联系我 邮箱862679370@qq.com

**Comment by catcherwong** [comment]
这个看上去就是请求接口超时，检查一下出现这个日志时，你的 pod 能不能正常访问到 nacos，如果不能就要排查一下网络这一块的问题，
