### ISSUE TITLE
客户端连接Nacos服务器报错

### ISSUE THREAD

**Issue by Zhao-Michael** [nacos-group/nacos-sdk-csharp#338]
## Describe what happened (or what feature you want)

客户端启动报错

## Describe what you expected to happen

启动不报错

## Related code

fail: Nacos.V2.Config.NacosConfigService[0]
[NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848/, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
[NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848/, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
[NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848/, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
[NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848/, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
[fixed-xxxxxxxxxxxxxx_8848-] [check-update] get changed dataId exception
System.Exception: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
at Nacos.V2.Config.Http.ServerHttpAgent.HttpRequest(String path, Dictionary2 headers, Dictionary2 paramValues, String encoding, Int64 readTimeoutMs, HttpMethod method)
at Nacos.V2.Config.Http.ServerHttpAgent.HttpPost(String path, Dictionary2 headers, Dictionary2 paramValues, String encoding, Int64 readTimeoutMs)
at Nacos.V2.Config.Impl.ConfigHttpTransportClient.CheckUpdateConfigStr(String probeUpdateString, Boolean isInitializingCacheList)
fail: Nacos.V2.Config.NacosConfigService[0]
longPolling error
System.Exception: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
at Nacos.V2.Config.Http.ServerHttpAgent.HttpRequest(String path, Dictionary2 headers, Dictionary2 paramValues, String encoding, Int64 readTimeoutMs, HttpMethod method)
at Nacos.V2.Config.Http.ServerHttpAgent.HttpPost(String path, Dictionary2 headers, Dictionary2 paramValues, String encoding, Int64 readTimeoutMs)
at Nacos.V2.Config.Impl.ConfigHttpTransportClient.CheckUpdateConfigStr(String probeUpdateString, Boolean isInitializingCacheList)
at Nacos.V2.Config.Impl.ConfigHttpTransportClient.CheckUpdateDataIds(List1 cacheDatas, List1 inInitializingCacheList)
at Nacos.V2.Config.Impl.ConfigHttpTransportClient.b__33_0(Object x) 

## Tell us your environment

- nacos-sdk-csharp version: 1.3.10
- nacos server version:  https://github.com/nacos-group/r-nacos  host in my server.

## Anything else we need to know?

可能是服务器或者DNS不太稳定，workaround 也许可以添加重试次数，或者让重试次数可配置？

https://github.com/nacos-group/nacos-sdk-csharp/blob/7afd0d2870298658152e00df0b526a8d08cc91a6/src/Nacos/V2/Config/Http/ServerHttpAgent.cs#L100

**Comment by catcherwong** [comment]
这个很明显是服务端有问题了，重试3次已经很多了，如果想要配置，倒是可以考虑加。
