### ISSUE TITLE
nacos使用默认端口&grpc可正常访问时，nacos-sdk-csharp控制台提示异常：Client not connected,current status: STARTING

### ISSUE THREAD

**Issue by qiaokuan1992** [nacos-group/nacos-sdk-csharp#339]
#### nacos server
我在局域网的Ubuntu Server 2204服务器（IP地址为192.168.100.254）中使用Docker启动了Nacos-Server单机实例，并且开放了8848、9848、9849等端口，配置文件如下：
```yaml
version: '3'
services: 
 nacos-node-1:
    image: "nacos/nacos-server:v2.4.3"
    container_name: nacos-node-1
    restart: on-failure:3
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - PREFER_HOSTZ_MODE=ip
      - MYSQL_SERVICE_HOST=192.168.100.254
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - NACOS_AUTH_ENABLE=true
      - SPRING_DATASOURCE_PLATFORM=mysql
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    privileged: true
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./logs/:/home/nacos/logs
      - ./data/:/home/nacos/data
    networks:
      nacos-network:
        ipv4_address: 172.40.0.4
        
networks:
  nacos-network:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
```
##### nuget包

在开发机上使用dotnet core 3.1创建了默认的WebAPI项目，并且在项目中安装了以下nuget包：
```sh
nacos-sdk-csharp:1.3.10
nacos-sdk-csharp.Extensions.Configuration:1.3.10
```
##### AppSetting.json

我根据仓库说明，修改了AppSetting.json文件：
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "common",
        "Group": "DEFAULT_GROUP"
      },
      {
        "Optional": false,
        "DataId": "demo",
        "Group": "DEFAULT_GROUP"
      }
    ],
    "Namespace": "397cc684-d728-477c-a6cc-5bcbaed72677", // Please set the value of Namespace ID !!!!!!!!
    //"Tenant": "397cc684-d728-477c-a6cc-5bcbaed72677",
    "ServerAddresses": [ "http://192.168.100.254:8848/" ],
    "UserName": "nacos",
    "Password": "nacos",
    //"AccessKey": "",
    //"SecretKey": "",
    //"EndPoint": "http://192.168.100.254:8848/",
    //"ConfigFilterAssemblies": [ "Nacos-Test" ],
    //"ConfigFilterExtInfo": "Nacos-Test ext infomation"
  }
}
```

##### Program.cs

我在Program.cs中进行了以下配置：
```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = CreateHostBuilder(args);

            builder.Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseNacosConfig(section: "NacosConfig", parser: null, logAction: null)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```

### 异常信息

当我启动项目时（启动控制台或者IIS Express），控制台提示以下信息：
```
info: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [subscribe] common+DEFAULT_GROUP+397cc684-d728-477c-a6cc-5bcbaed72677
info: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [subscribe] demo+DEFAULT_GROUP+397cc684-d728-477c-a6cc-5bcbaed72677
fail: Nacos.V2.Config.NacosConfigService[0]
      async listen config change error
Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
   at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
   at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
   at Nacos.V2.Config.Impl.ConfigRpcTransportClient.ExecuteConfigListen()
fail: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [sub-server-error] dataId=common, group=DEFAULT_GROUP, tenant=397cc684-d728-477c-a6cc-5bcbaed72677, code=Client not connected,current status: STARTING
Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
   at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
   at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
   at Nacos.V2.Config.Impl.ConfigRpcTransportClient.QueryConfig(String dataId, String group, String tenant, Int64 readTimeous, Boolean notify)
warn: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [get-config] get from server error, dataId=common, group=DEFAULT_GROUP, tenant=397cc684-d728-477c-a6cc-5bcbaed72677, msg=Client not connected,current status: STARTING
warn: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [get-config] get snapshot ok, dataId=common, group=DEFAULT_GROUP, tenant=397cc684-d728-477c-a6cc-5bcbaed72677, config=
warn: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      MS Config Query config error, dataid=common, group=DEFAULT_GROUP, tenant=397cc684-d728-477c-a6cc-5bcbaed72677
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.IO.StringReader..ctor(String s)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
   at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
fail: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      Load config error
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.IO.StringReader..ctor(String s)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
   at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:15000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\Workspace\Demo\Nacos-Test
fail: Nacos.V2.Config.NacosConfigService[0]
      async listen config change error
Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
   at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
   at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
   at Nacos.V2.Config.Impl.ConfigRpcTransportClient.ExecuteConfigListen()
```
![image](https://github.com/user-attachments/assets/bece1195-a26f-44c9-ac1f-2a839685e2ab)

### 检查
我在服务器上查看开放的端口，8848、9848、9849等端口都正常开放，并且在本地通过telnet或其他socket客户端可正常连接这些端口。

### 目标
我应该如何进行更多测试，修复这个问题？

## Tell us your environment

- nacos-sdk-csharp version: 1.3.10
- modular : [e.g. naming/config/msconfig/....]
- nacos server version: 2.4.3
- how to host nacos server : docker

**Comment by kamazheng** [comment]
和楼主一样，我更改了配置，服务器用Nginx代理Grpc：

> Server: 
>     NACOS 2.4.3
> SDK:
> 
>     <PackageReference Include="nacos-sdk-csharp" Version="1.3.10" />
>     <PackageReference Include="nacos-sdk-csharp.AspNetCore" Version="1.3.10" />
>     <PackageReference Include="nacos-sdk-csharp.Extensions.Configuration" Version="1.3.10" />

```

// Add Nacos configuration
var nacosCf = appbuilder.Configuration.GetSection("NacosConfig");
appbuilder.Configuration.AddNacosV2Configuration(nacosCf, logAction:
    x => x.AddConsole());

server {
    listen 443 ssl;
    server_name xxxx.com;
    ssl_certificate xxx.crt;
    ssl_certificate_key xxx.key;
    location / {
        grpc_pass grpc://nacos:9848;
    }
}

{
  "NacosConfig": {
    "Listeners": [
      {
        "Optional": false,
        "DataId": "TTT",
        "Group": "TTT"
      }
    ],
    "Namespace": "Development", // Please set the value of Namespace ID !!!!!!!!
    "ServerAddresses": [ "https://xxxx.com/" ],
    "UserName": "xxx",
    "Password": "xxx",
    "AccessKey": "serverIdentity",
    "SecretKey": "xxx"
  }
}
````

再次运行时报错：

> fail: Nacos.V2.Config.NacosConfigService[0]
>       login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
> fail: Nacos.V2.Config.NacosConfigService[0]
>       login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
> info: Nacos.V2.Config.NacosConfigService[0]
>       [config_rpc_client] [subscribe] TTT+TTT+Development
> fail: Nacos.V2.Config.NacosConfigService[0]
>       login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
> fail: Nacos.V2.Config.NacosConfigService[0]
>       login failed: Content-Type 'application/x-www-form-urlencoded' is not supported

**Comment by kamazheng** [comment]
If I add both Http and Rpc server:

```
# nacos rpc
server {
    listen 443 ssl;
    http2 on;
    server_name xxxx.com;
    ssl_certificate xxx.crt;
    ssl_certificate_key xxx.key;
    location / {
        grpc_pass grpc://nacos:9848;
    }
}
# nacos http
server {
    listen 80;
    server_name xxxx.com;
    location / {
        proxy_pass http://nacos:8848;
    }
}

"ServerAddresses": [ "https://xxxx.com/","http://xxxx.com/" ],

```



The error:

> fail: Nacos.V2.Config.NacosConfigService[0]
      login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
fail: Nacos.V2.Config.NacosConfigService[0]
      login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
info: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [subscribe] TTT+TTT+Development
fail: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [sub-server-error] dataId=TTT, group=TTT, tenant=Development, code=Client not connected,current status: STARTING
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
         at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.QueryConfig(String dataId, String group, String tenant, Int64 readTimeous, Boolean notify)
fail: Nacos.V2.Config.NacosConfigService[0]
      async listen config change error
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
         at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.ExecuteConfigListen()
warn: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [get-config] get from server error, dataId=TTT, group=TTT, tenant=Development, msg=Client not connected,current status: STARTING
warn: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [get-config] get snapshot ok, dataId=TTT, group=TTT, tenant=Development, config=
warn: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      MS Config Query config error, dataid=TTT, group=TTT, tenant=Development
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.IO.StringReader..ctor(String s)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
fail: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      Load config error
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.IO.StringReader..ctor(String s)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft
         
         
         The Nginx logs:

> 10.221.163.60 - - [13/Dec/2024:03:02:55 +0000] "POST /nacos/v1/auth/users/login HTTP/1.1" 415 76 "-" "-" "-"
10.221.163.60 - - [13/Dec/2024:03:03:00 +0000] "POST /nacos/v1/auth/users/login HTTP/1.1" 415 76 "-" "-" "-"



>

**Comment by qiaokuan1992** [comment]
> 和楼主一样，我更改了配置，服务器用Nginx代理Grpc：
> 
> > Server:
> > NACOS 2.4.3
> > SDK:
> > ```
> > <PackageReference Include="nacos-sdk-csharp" Version="1.3.10" />
> > <PackageReference Include="nacos-sdk-csharp.AspNetCore" Version="1.3.10" />
> > <PackageReference Include="nacos-sdk-csharp.Extensions.Configuration" Version="1.3.10" />
> > ```
> 
> ```
> 
> // Add Nacos configuration
> var nacosCf = appbuilder.Configuration.GetSection("NacosConfig");
> appbuilder.Configuration.AddNacosV2Configuration(nacosCf, logAction:
>     x => x.AddConsole());
> 
> server {
>     listen 443 ssl;
>     server_name xxxx.com;
>     ssl_certificate xxx.crt;
>     ssl_certificate_key xxx.key;
>     location / {
>         grpc_pass grpc://nacos:9848;
>     }
> }
> 
> {
>   "NacosConfig": {
>     "Listeners": [
>       {
>         "Optional": false,
>         "DataId": "TTT",
>         "Group": "TTT"
>       }
>     ],
>     "Namespace": "Development", // Please set the value of Namespace ID !!!!!!!!
>     "ServerAddresses": [ "https://xxxx.com/" ],
>     "UserName": "xxx",
>     "Password": "xxx",
>     "AccessKey": "serverIdentity",
>     "SecretKey": "xxx"
>   }
> }
> ```
> 
> 再次运行时报错：
> 
> > fail: Nacos.V2.Config.NacosConfigService[0]
> > login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
> > fail: Nacos.V2.Config.NacosConfigService[0]
> > login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
> > info: Nacos.V2.Config.NacosConfigService[0]
> > [config_rpc_client] [subscribe] TTT+TTT+Development
> > fail: Nacos.V2.Config.NacosConfigService[0]
> > login failed: Content-Type 'application/x-www-form-urlencoded' is not supported
> > fail: Nacos.V2.Config.NacosConfigService[0]
> > login failed: Content-Type 'application/x-www-form-urlencoded' is not supported

根据已知的资料，nginx的配置需要把Grpc(9848)配置成tcp，不能使用HTTP。同时Namespace需要使用命名空间的ID（例如：397cc684-d728-477c-a6cc-5bcbaed72677），而不是名称（例如：Development）。
在这个配置中，需要保证使用的端口间隔与服务器端默认配置相同（8848-1000，8848，8848+1000，8848+1001）

**Comment by liu19980618** [comment]
服务器上部署后，直接映射8848、9848接口出来，还是报楼主一样的错误，但是服务器上部署应用就没问题

**Comment by scrapstation** [comment]
+1
<img width="1100" height="732" alt="Image" src="https://github.com/user-attachments/assets/519fdbf7-e93a-4ba9-ad98-3e02f0630d90" />

**Comment by scrapstation** [comment]
找了半天问题，结果发现是因为开启了fq代理导致的
