### ISSUE TITLE
Calling GetInstanceAsync throw exception when the instance does not exist

### ISSUE THREAD

**Issue by bambookai** [nacos-group/nacos-sdk-csharp#41]
使用的版本是0.5.0，导致异常原因是Instance不存在，直接用PostMan调用Nacos API接口返回 **HTTP500 caused: no service Phoenix.Service@@OpenGateway found!;**，但是nacos sdk响应的内容与实际情况不符，返回如下错误：

### 描述：
> System.ArgumentException:“An item with the same key has already been added. Key: app”

### 堆栈：
`   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Nacos.Naming.Http.NamingProxy.InjectSecurityInfo(HttpRequestMessage requestMessage, Dictionary`2 paramValues)
   at Nacos.Naming.Http.NamingProxy.<CallServerAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Nacos.Naming.Http.NamingProxy.<ReqApiAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nacos.NacosNamingClient.<GetInstanceAsync>d__13.MoveNext()`

我如何判断一个服务实例（Instance）是否被注册。
感谢支持！

**Comment by catcherwong** [comment]
@bambookai 谢谢您对这个项目感兴趣！

>System.ArgumentException:“An item with the same key has already been added. Key: app”

这个异常是调用查询接口失败后，重试时导致重复添加kv时引发的异常。这个异常晚点会修复掉。

> 我如何判断一个服务实例（Instance）是否被注册。

这个接口查询失败的时候会返回非200的状态码，所以都是会抛出异常的。

您可以根据服务名去找到列表，然后判断列表里面是否有对应的instance信息。

-------

Thanks for your interest in this project.

> System.ArgumentException:“An item with the same key has already been added. Key: app”

This exception is caused by repeated addition of KV after calling query interface failure. This exception will be fixed later.

> 我如何判断一个服务实例（Instance）是否被注册。

When this interface fails to query, it will return a non-200 status code, so it will throw an exception.

You can find the list according to the service name, and then judge whether there is corresponding instance information in the list.

**Comment by catcherwong** [comment]
have a try with version v0.8.0-alpha20200922142407 .

**Comment by bambookai** [comment]
> have a try with version v0.8.0-alpha20200922142407 .

引用了这个版本之后，确实修复这个问题。
额外再提一个建议，当Instance不存在时，能否将GetInstanceResult以NULL的形式返回，而不是直接抛出异常，让调用者可以更简单得处理Instance不存在的情况。
谢谢回复 ：）

**Comment by catcherwong** [comment]
> 当Instance不存在时，能否将GetInstanceResult以NULL的形式返回，而不是直接抛出异常，让调用者可以更简单得处理Instance不存在的情况。

这个后面会考虑如何让使用方用的更加方便，谢谢您的建议。:smile:

----------

This will be considered how to make the user more convenient in the future, thank you for your advice. :smile:
