### ISSUE TITLE
System.ArgumentNullException:“Value cannot be null. ”

### ISSUE THREAD

**Issue by sports-boy** [nacos-group/nacos-sdk-csharp#44]
AspNetCore3.1

<PackageReference Include="nacos-sdk-csharp-unofficial.Extensions.Configuration" Version="0.5.0" />

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. 
  Source=System.Runtime.Extensions
  StackTrace:
   at System.IO.StringReader..ctor(String s)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
   at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
   at Nacos.Microsoft.Extensions.Configuration.NacosConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at _01_SB.SampleApi.Program.Main(String[] args) in E:\源码\SB\Sources\04-Samples\01-SB.SampleApi\Program.cs:line 19

  此异常最初是在此调用堆栈中引发的: 
    System.IO.StringReader.StringReader(string)
    Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(string)
    Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(string)
    Nacos.Microsoft.Extensions.Configuration.NacosConfigurationProvider.Load()
    Microsoft.Extensions.Configuration.ConfigurationRoot.ConfigurationRoot(System.Collections.Generic.IList<Microsoft.Extensions.Configuration.IConfigurationProvider>)
    Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
    Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
    Microsoft.Extensions.Hosting.HostBuilder.Build()
    _01_SB.SampleApi.Program.Main(string[]) (位于 Program.cs 中)

**Comment by catcherwong** [comment]
@sports-boy  谢谢您对这个项目感兴趣！


看了一下您的这个异常，是读取nacos里面的配置后，进行解析的时候发现配置是null值。

您可以检查一下配置的`DataId` 在nacos里面是否有具体的值呢？

--------

Thanks for your interest in this project.

This exception is due to after reading configuration from nacos, the parser can not parse the value.

Please check the value of the `DataId` configured in `appsettings`

**Comment by catcherwong** [comment]
Any feedback for this issue?
