### ISSUE TITLE
Register instance error 401

### ISSUE THREAD

**Issue by Uchiha-Peng** [nacos-group/nacos-sdk-csharp#87]
nacos 2.0  in docker,
asp.net core 3.1
配置如下
![image](https://user-images.githubusercontent.com/20633089/114374469-404be180-9bb6-11eb-83f5-7db1e709f05b.png)

startup.cs注入如下
```
services.AddNacosAspNet(Configuration);
```
Nuget依赖如下

![image](https://user-images.githubusercontent.com/20633089/114374697-81dc8c80-9bb6-11eb-8a72-40a497f10037.png)

注册出现错误，错误信息如下

```
[17:36:45 ERR] register instance error, count = 1
Nacos.V2.Exceptions.NacosException: Request nacos server failed: -401, Client not connected,current status: 2
   at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RequestToServer[T](AbstractNamingRequest request)
   at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
   at Nacos.V2.Naming.Remote.NamingClientProxyDelegate.RegisterServiceAsync(String serviceName, String groupName, Instance instance)
   at Nacos.V2.Naming.NacosNamingService.RegisterInstance(String serviceName, String groupName, Instance instance)
   at Nacos.AspNetCore.V2.RegSvcBgTask.StartAsync(CancellationToken cancellationToken)
```

**Comment by catcherwong** [comment]
@Uchiha-Peng  如果是用 docker 的话，请确保端口是否映射出来了。

参考下面这个文档：

https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by catcherwong** [comment]
```
 ports:
    - "8848:8848"
    - "9848:9848"
```

**Comment by Uchiha-Peng** [comment]
感谢，已经成功了，确实是没有映射9849端口导致的，Docker命令如下
```
docker run -d -p 8848:8848 -p 9848:9848 --restart=always --privileged=true -e MODE=standalone -v /data/nacos/logs:/home/nacos/logs --name nacos nacos/nacos-server:latest
```
