### ISSUE TITLE
Register instance error 401，nacos 1.2.1

### ISSUE THREAD

**Issue by carldai0106** [nacos-group/nacos-sdk-csharp#96]
使用 阿里云微服务引擎MSE 中的注册配置中心 nacos 1.2.1
asp.net core 3.1
配置信息如下：
```json

"nacos": {
        "ServerAddresses": [ "http://xxxx.nacos-ans.mse.aliyuncs.com:8848" ],
        "DefaultTimeOut": 15000,
        "Namespace": "",
        "ListenInterval": 1000,
        "ServiceName": "CT.TestNacos.WebApi",
        "RegisterEnabled": true,
        "Port": 5005
    }

```
如果使用下面方式是可以注册服务成功的

```json
// 该方法已声明在后期版本中将移除
 services.AddNacosAspNetCore(Configuration);
```

当变更为下面方式，出现401错误

```json
services.AddNacosAspNet(Configuration);
```
错误信息如下：

```json
 register instance error, count = 1
Nacos.V2.Exceptions.NacosException: Request nacos server failed: -401, Client not connected,current status: 2
   at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RequestToServer[T](AbstractNamingRequest request) in E:\MyProject\Study\nacos-sdk-csharp-1.0.3\src\Nacos\V2\Naming\Remote\Grpc\NamingGrpcClientProxy.cs:line 183
   at Nacos.V2.Naming.Remote.Grpc.NamingGrpcClientProxy.RegisterServiceAsync(String serviceName, String groupName, Instance instance) in E:\MyProject\Study\nacos-sdk-csharp-1.0.3\src\Nacos\V2\Naming\Remote\Grpc\NamingGrpcClientProxy.cs:line 121
   at Nacos.V2.Naming.Remote.NamingClientProxyDelegate.RegisterServiceAsync(String serviceName, String groupName, Instance instance) in E:\MyProject\Study\nacos-sdk-csharp-1.0.3\src\Nacos\V2\Naming\Remote\NamingClientProxyDelegate.cs:line 80
   at Nacos.V2.Naming.NacosNamingService.RegisterInstance(String serviceName, String groupName, Instance instance) in E:\MyProject\Study\nacos-sdk-csharp-1.0.3\src\Nacos\V2\Naming\NacosNamingService.cs:line 159
   at Nacos.AspNetCore.V2.RegSvcBgTask.StartAsync(CancellationToken cancellationToken) in E:\MyProject\Study\nacos-sdk-csharp-1.0.3\src\Nacos.AspNetCore\V2\RegSvcBgTask.cs:line 93
```

**Comment by catcherwong** [comment]
@carldai0106 谢谢您对这个项目感兴趣。

根据错误信息，sdk这一块是用了 grpc 和 nacos 1.2.1 进行了交互，这个是不行的！！

因为 nacos 2.0 及以上版本才支持 grpc。

`services.AddNacosAspNet(Configuration);`  这个默认是采用grpc和服务端(2.0及以上)交互的，如果确实需要和低版本的服务端交互，把 `NamingUseRpc` 这个配置项设为false ，就会用 http 的方式去交互。

` services.AddNacosAspNetCore(Configuration);` 这种方式可以，是因为这个是基于1.x的服务端开发的，用的是http。

**Comment by carldai0106** [comment]
好的，谢谢。
